version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["100000token", "100000000stake"]
  - name: stan
    coins: ["50000token", "100000000stake"]
  - name: hugo
    coins: ["60000token", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5000token", "100000stake"]
